### ISSUE TITLE
plan for reducing startup time when many vanity paths are present

### ISSUE THREAD

**Issue by reschke** [reschke/sling-org-apache-sling-resourceresolver#4]
1. re-introduce regular persistence of bloom filter, but (a) in repository and (b) triggered by Sling scheduler
2. on startup:
    1. read bloom filter; if present, switch to "incompleteCache" mode, finish startup, and start full repo query in background
    2. otherwise, keep slow startup (run the full query synchronously)
3. additionally: modify query so it uses paging and users do not have to bump up query limits

Effects:

1. Startup will be quick unless for the first start
2. vanity paths will work immediately, although with a higher system load during initialization

TODO:

Simplify process of configuring bloom filter size

**Comment by joerghoh** [comment]
* the dumped bloom filter should be stored in a binary
* how do you handle support for clustering? 
* please ensure that the sling-id is not involved (in a cloning process the startup can be executed by an instance with a new id, but even in that case the persisted bloom filter should be used)

**Comment by reschke** [comment]
1) yes
2) persistence of the bloom filter will be done by a sling scheduler task running only on one node
3) sling-id will not be involved

(Thanks for the feedback!)

**Comment by joerghoh** [comment]
> Summary of where we are (in branch "bgquery"):
> 
>     * there's an OSGi config for moving the query to a background task (default "false")
> 
>     * while running the background query - when the cache is not ready yet - foreground query results are cached in a temporarily LRU cache (max 10000 entries); this includes "not founds"
> 
>     * while running the query (either case), events are not processed but enqueued, and only processed after the query finishes
> 
> 
> This allows async init of the ResourceResolver, solving the issue of slow startup due to many vanity paths
> 
> Todo;
> 
>     * run the query in "paged" mode, so the query limit does not need to be overridden
> 
>     * consider aliases
> 
> 
> Note:
> 
> no new persistence (fs or repo) was needed.

**Comment by reschke** [comment]
It is the same performance that we already get when the max. cache size is exceeded. Because of the additional load a cache was added (see above).

I'm not against a metric, but this is a one-off operation; does it make sense to have a metric here?

**Comment by joerghoh** [comment]
I think it does, because it allows us to calculate if and how much this background query is exceeding the completion of the startup of the application. A log entry with the same data might be useful as well.

**Comment by reschke** [comment]
log entry is already present
